// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatBoard: typeof import('./src/components/ChatBoard.vue')['default']
    ColorPen: typeof import('./src/components/ColorPen.vue')['default']
    DrawDialog: typeof import('./src/components/DrawDialog.vue')['default']
    Eraser: typeof import('./src/components/Eraser.vue')['default']
    HomeBackground: typeof import('./src/components/HomeBackground.vue')['default']
    MainButton: typeof import('./src/components/MainButton.vue')['default']
    MyCanvas: typeof import('./src/components/MyCanvas.vue')['default']
    Pigment: typeof import('./src/components/Pigment.vue')['default']
    Recovery: typeof import('./src/components/Recovery.vue')['default']
    Reset: typeof import('./src/components/Reset.vue')['default']
    Revoke: typeof import('./src/components/Revoke.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Subjest: typeof import('./src/components/Subjest.vue')['default']
  }
}

export {}
